[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API routes to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Static files - serve directly
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle specific routes for static files
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

# Handle logos
[[redirects]]
  from = "/logos/*"
  to = "/logos/:splat"
  status = 200

# SPA fallback for client-side routing - MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
