[build]
  # Build command for the monorepo structure
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  # Publish directory - Next.js output
  publish = "apps/web/.next"
  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Use npm instead of pnpm to avoid lockfile issues
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  # Disable pnpm auto-detection
  NPM_CONFIG_FUND = "false"

# API routes are handled by Next.js API functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Next.js chunks
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
